# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2025-2026 Afeef Janjua
"""add summary templates

Revision ID: 2432691ecffe
Revises: 03468ac9f8b1
Create Date: 2026-03-04 16:26:29.609918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2432691ecffe'
down_revision: Union[str, None] = '03468ac9f8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('meeting', sa.Column('template_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'meeting', 'summarytemplate', ['template_id'], ['id'])
    op.add_column('user', sa.Column('default_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'summarytemplate', ['default_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'default_template_id')
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'template_name')
    op.drop_column('meeting', 'template_id')
    # ### end Alembic commands ###
